### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by sergiokopplin** [sergiokopplin/indigo#89]
add theme:
- [x] https://drjekyllthemes.github.io/
- [x] http://jekyllthemes.io/

---

update screen-shot:
- [x] http://jekyllthemes.org/

**Comment by sergiokopplin** [comment]
done!
